//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "book")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub hash: String,
    pub user_id: i32,
    pub file_tyoe: i32,
    pub email_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::email::Entity",
        from = "Column::EmailId",
        to = "super::email::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Email,
    #[sea_orm(
        belongs_to = "super::file_type::Entity",
        from = "Column::FileTyoe",
        to = "super::file_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FileType,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::email::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Email.def()
    }
}

impl Related<super::file_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileType.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
