//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::book::Entity as Book;
pub use super::email::Entity as Email;
pub use super::file_type::Entity as FileType;
pub use super::user::Entity as User;
